export { default as Home } from './Home';
export { default as MyProfile } from './MyProfile';
export { default as TwitchGaming } from './TwitchGaming';
export { default as YoutubeGaming } from './YoutubeGaming';
export { default as Register } from './auth/Register';
export { default as Login } from './auth/Login';
export { default as EmailConfirm } from './EmailConfirm';
export { default as PrivacyPolicy } from './legals/PrivacyPolicy';
export { default as TermsAndConditions } from './legals/TermsAndConditions';
