export { default as Games } from './Games/Games';
export { default as GameList } from './GameList';
export { default as GameDetails } from './GameDetails';
export { default as Nav } from './Nav';
export { default as SideMenu } from './SideMenu';
export { default as Modal } from './Modal';
export { default as Loader } from './Loader/Loader';
export { default as Logo } from './Logo';
export { default as ModalLoader } from './ModalLoader';
